Repository photonle/Photon, pull requests merged in 2019-11, with the labels that each got.

#63 Addition to the original TMD Siren
  lua/autorun/photon/library/emv_sirens.lua
  sound/emv/sirens/federal sig tm/pemv_tmjingle.wav
Labels: library

#71 Illumination Error Fix
  lua/autorun/photon/sh_emv_helper.lua
Labels: bug

#73 EMVU.Configurations support in EMV.OverwriteIndex
  lua/autorun/photon/library/default/default_lw_charger.lua
  lua/autorun/photon/library/default/default_lw_impala.lua
  lua/autorun/photon/library/default/default_lw_suburban_und.lua
  lua/autorun/photon/library/default/default_lw_tahoe.lua
  lua/autorun/photon/library/default/default_schmal_fpiu16.lua
  lua/autorun/photon/library/default/default_schmal_tahoe16.lua
  lua/autorun/photon/library/default/default_talon_suburban.lua
  lua/autorun/photon/library/default/default_tdm_cvpi.lua
  lua/autorun/photon/library/default/default_tdm_dc12.lua
  lua/autorun/photon/library/default/default_tdm_dc12_old.lua
  lua/autorun/photon/library/default/default_tdm_fpis.lua
  lua/autorun/photon/library/default/default_tdm_hsv.lua
  lua/autorun/photon/sh_emv_vehicles.lua
Labels: library

#66 DT Var Hotfix
  lua/autorun/photon/cl_emv_meta.lua
  lua/autorun/photon/cl_photon_hud.lua
  lua/autorun/photon/cl_photon_meta.lua
  lua/autorun/photon/sh_emv_config.lua
  lua/autorun/photon/sh_emv_meta.lua
  lua/autorun/photon/sv_emv_meta.lua
  lua/autorun/photon/sv_emv_net.lua
  lua/autorun/photon/sv_photon_hooks.lua
  lua/autorun/photon/sv_photon_meta.lua
Labels: bug

#75 Fix for submodel liveries.
  lua/autorun/photon/cl_emv_livery.lua
  lua/autorun/photon/sh_emv_helper.lua
  lua/autorun/photon/sv_emv_meta.lua
Labels: bug

#76 Added a simple system for offsetting the HUD.
  lua/autorun/photon/cl_photon_hud.lua
Labels: enhancement

#77 EMVU Auto Illumination Colors
  lua/autorun/photon/sh_emv_vehicles.lua
Labels: enhancement

#78 Driver SF Standard Library.
  .github/workflows/library.yml
  lua/autorun/photon/library/auto/driver_lightbar.lua
  lua/autorun/photon/library/auto/driver_pushbar.lua
Labels: library

#79 LW's Police Package Library.
  lua/autorun/photon/library/auto/lw_arrowboard.lua
  lua/autorun/photon/library/auto/lw_interior_led.lua
  lua/autorun/photon/library/auto/lw_interior_led_split.lua
  lua/autorun/photon/library/auto/lw_interior_lightbar.lua
  lua/autorun/photon/library/auto/lw_matrixboard.lua
Labels: library

#80 Automatic GMA builder for releases.
  .github/builder/.gitignore
  .github/builder/build.php
  .github/builder/composer.json
  .github/builder/composer.lock
  .github/workflows/builds.yml
Labels: ci/cd

#82 Switch the tag builder to use an iterator instead of the funky shit I used before.
  .github/builder/build.php
  .github/builder/composer.json
  .github/builder/composer.lock
Labels: ci/cd, enhancement

#88 HUD Opacity Fix.
  lua/autorun/photon/cl_photon_hud.lua
Labels: bug

#89 Only push doc changes when they actually change.
  .github/new-docs.sh
  .github/workflows/documentation.yml
Labels: ci/cd, enhancement

#95 Backwards Toggle & Custom Keys
  lua/autorun/photon/cl_emv_listener.lua
  lua/autorun/photon/cl_photon_settings.lua
  lua/autorun/photon/cl_photon_toolmenu.lua
  lua/autorun/photon/sv_emv_meta.lua
  lua/autorun/photon/sv_emv_net.lua
Labels: bug, enhancement
